// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbEk_1lDMvmMokbp7FVlA8BD1cApJb--M',
    appId: '1:87504596017:web:ebb439d3c3002b7cf1f910',
    messagingSenderId: '87504596017',
    projectId: 'bukizz1',
    authDomain: 'bukizz1.firebaseapp.com',
    storageBucket: 'bukizz1.appspot.com',
    measurementId: 'G-1XQ3QSXWD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmx20-mEPRqrJqA-CeTB55DHGQgW0Eswo',
    appId: '1:87504596017:android:c678028905b45d1af1f910',
    messagingSenderId: '87504596017',
    projectId: 'bukizz1',
    storageBucket: 'bukizz1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMZGo9aX68TOuMhqrppk1Kq9Qv3Cbxxs',
    appId: '1:87504596017:ios:69b625da9b8a079df1f910',
    messagingSenderId: '87504596017',
    projectId: 'bukizz1',
    storageBucket: 'bukizz1.appspot.com',
    androidClientId: '87504596017-7vbv5np5lf6d7n3qe1f396a54j6hpbc6.apps.googleusercontent.com',
    iosClientId: '87504596017-j7oq74j66apblga91lo8i05gdc5lji1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.bukizz1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkMZGo9aX68TOuMhqrppk1Kq9Qv3Cbxxs',
    appId: '1:87504596017:ios:e254151ef8e12880f1f910',
    messagingSenderId: '87504596017',
    projectId: 'bukizz1',
    storageBucket: 'bukizz1.appspot.com',
    androidClientId: '87504596017-7vbv5np5lf6d7n3qe1f396a54j6hpbc6.apps.googleusercontent.com',
    iosClientId: '87504596017-0rkkrsq2pa04t9dg9m0g97m0bcdbtagn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bukizz1.RunnerTests',
  );
}
